[theme]
theme = "ctp-mocha"

[theme.overrides]
good_bg = "#00af00"
warning_bg = "#afaf00"
critical_bg = "#af0a00"
critical_fg = "#ffffff"
separator = "native"
alternating_tint_bg = "none"
alternating_tint_fg = "none"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon $combo $play "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) ($mem_used) / $mem_total "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "time"
interval = 60

[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R', l:en_US) "
short = " $icon $timestamp.datetime(f:%R) "
